services:
  frontend:
    build:
      context: ./frontend-vite
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - ./.env
    volumes:
      - ./frontend-vite/src:/app/src:rw
    links:
      - backend:backend
    depends_on:
      - backend
      - kc
  backend:
    build:
      context: ./backend
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - kc:kc
    depends_on:
      - kc
  kc:
    image: quay.io/keycloak/keycloak:26.1
    container_name: kc
    ports:
      - '8081:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOG_LEVEL=DEBUG
      - KEYCLOAK_IMPORT_LOG_LEVEL=DEBUG
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realmdata:/opt/keycloak/data/import
