services:
  frontend:
    build:
      context: ./frontend-vite
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - ./.env
    volumes:
      - ./frontend-vite/src:/app/src:rw
    links:
      - backend:backend
    depends_on:
      - backend
      - kc
    networks:
      - mynet
  backend:
    build:
      context: ./backend
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - kc:kc
    depends_on:
      - kc
    networks:
      - mynet
  kc:
    image: quay.io/keycloak/keycloak:26.1
    container_name: kc
    ports:
      - '8081:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOG_LEVEL=DEBUG
      - KEYCLOAK_IMPORT_LOG_LEVEL=DEBUG
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realmdata:/opt/keycloak/data/import
    networks:
      - mynet
  mini:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - 9100:9100
      - 9101:9101
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=profit
      - MINIO_ROOT_PASSWORD=profit123
      - MINIO_DEFAULT_BUCKETS=profit
    command: server /data --console-address ":9101"
    networks:
      - mynet
  frontend-next:
    build:
      context: ./frontend-next
    container_name: frontend-next
    ports:
      - "3000"
    networks:
      - mynet

  nginx-next:
      image: nginx:1.27-alpine
      container_name: nginx-next
      ports:
        - "80:80"
      volumes:
        - ./frontend-next/nginx-next.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - frontend-next
      networks:
        - mynet

networks:
  mynet:
    driver: bridge