services:
  react:
    build:
      context: ./frontend-vite
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - ./.env
    volumes:
      - ./frontend-vite/src:/app/src:rw
    links:
      - api:api
    depends_on:
      - api
  api:
    build:
      context: ./backend
    ports:
      - ${API_PORT}:${API_PORT}
