import {IParameter, ITask} from "~/utilities/types/models.ts";

export const people: IParameter[] = [{id: "179", label: "Halil Kemal TAŞKIN"},
    {id: "346", label: "Abdurrahman Gül"},
    {id: "351", label: "Ali Karaduman"},
    {id: "417", label: "Özge Tahmazoğlu"},
    {id: "372", label: "Mustafa Sarı"},
    {id: "53", label: "Gökhan ÇAPAR"},
    {id: "373", label: "Necip Akça"},
    {id: "228", label: "Erkay Kahya"},
    {id: "334", label: "Sabiha Yorulmaz"},
    {id: "335", label: "Seçkin Cem Ergin"},
    {id: "336", label: "Selçuk Öncü"},
    {id: "337", label: "Serkan Aktaş"},
    {id: "338", label: "Sinan Ulutaş"},
    {id: "341", label: "Volkan Cıvdı"},
    {id: "416", label: "Melike Akpınar"},
    {id: "370", label: "Merih Güz"},
    {id: "413", label: "Ali Ergin"},
    {id: "138", label: "İbrahim TAŞÇI"},
    {id: "386", label: "Muhammed Yamaç Türker"},
    {id: "307", label: "Ahmet Korana"},
    {id: "415", label: "Ali Fuat Asar"},
    {id: "81", label: "Halil İbrahim BAYKAL"},
    {id: "214", label: "Ömer Hakan KILIÇ"},
    {id: "389", label: "Çağdaş Aktaş"},
    {id: "390", label: "Nurcan Güven Ermut"},
    {id: "321", label: "İbrahim Hakkı Karagözoğlu"},
    {id: "402", label: "Onur Başkaya"},
    {id: "400", label: "Fatma Topcu"},
    {id: "208", label: "Ömer Şamil AÇBA"},
    {id: "396", label: "Hikmet Yavuz"},
    {id: "374", label: "Oğuzhan Mustafa Tarhan"},
    {id: "376", label: "Özgenur Erkazan"},
    {id: "385", label: "Samet Yılmaz"},
    {id: "379", label: "Selin Zeydan"},
    {id: "378", label: "Selçuk Taşkın"},
    {id: "367", label: "Mehmet Bozdemir"},
    {id: "78", label: "Emre ASLAN"},
    {id: "229", label: "Erol Yarar"},
    {id: "204", label: "Kazım EFENDİOĞLU"},
    {id: "149", label: "Yusuf Gökbey GÖK"},
    {id: "184", label: "Tuna ASLAN"},
    {id: "395", label: "Talha Aksoy"},
    {id: "236", label: "Emre Deniz"},
    {id: "38", label: "Burak EMRİ"},
    {id: "107", label: "Eren  TEKKEŞİN"},
    {id: "109", label: "Asiye MANYASLI"},
    {id: "127", label: "İbrahim İŞİM"},
    {id: "113", label: "Emine HOŞGÖR"},
    {id: "159", label: "Ahmet YAPICI"},
    {id: "198", label: "Muhanad YOUNİS"},
    {id: "221", label: "Hamza Kağan GÜNAL"},
    {id: "222", label: "Mehmet İNCE"},
    {id: "235", label: "Elif Gökçe Köksal"},
    {id: "242", label: "Nihat Kihtir"},
    {id: "79", label: "Ethem AYGÜZER"},
    {id: "62", label: "Kezban TİMUÇİN"},
    {id: "85", label: "Kerem DAĞCI"},
    {id: "87", label: "Mehmet ASLAN"},
    {id: "88", label: "Mehmet COŞKUN"},
    {id: "89", label: "Mehmet Emin YÜCEANT"},
    {id: "91", label: "Menderes UYAR"},
    {id: "92", label: "Muhammet KARAKAYA"},
    {id: "93", label: "Murat SAYIN"},
    {id: "61", label: "Serhat ŞİMŞEK"},
    {id: "103", label: "Yasin ÖZGÜL"},
    {id: "106", label: "Yusuf SEVİNDİK"},
    {id: "197", label: "Mehmed Sıddık ATLI"},
    {id: "295", label: "Salih Akdaş"},
    {id: "243", label: "Ali Engin Aksoy"},
    {id: "244", label: "Ali Onur Karasu"},
    {id: "245", label: "Ali Osman Toprak"},
    {id: "246", label: "Cenab Necdet Hatipoğlu"},
    {id: "247", label: "Cengizhan Altınok"},
    {id: "249", label: "Dilek Türkeri"},
    {id: "250", label: "Emrullah Çelik"},
    {id: "251", label: "Engin Çirik"},
    {id: "252", label: "Ferhat Uluşen"},
    {id: "253", label: "Gökhan Biçer"},
    {id: "254", label: "Hamza Durdu"},
    {id: "255", label: "Hüseyin Gedikli"},
];

export const statuses: IParameter[] = [{id: "1", label: "Sahipsiz"},
    {id: "2", label: "Atandı"},
    {id: "3", label: "Devam Ediyor"},
    {id: "4", label: "Tamamlandı"},
    {id: "5", label: "İptal"},];


export const emptyTask: ITask = {
    id: undefined,
    title: undefined,
    description: undefined,
    reportedBy: undefined,
    assignedBy: undefined,
    assignedTo: undefined,
    status: statuses[0]
};
