spring:
  application:
    name: backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/company-services
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  jpa:
    open-in-view: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
jwt:
  auth:
    converter:
      resource-id: projem-task
      principal-attribute: preferred_username
app:
  cors:
    allowed-origins: http://localhost:3000
javers:
  mongodb:
    uri: mongodb://localhost:27017/myframe1
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
logging:
  level:
#    org.springframework.security: debug
    org.h2.jdbc: debug
server:
  port: 8080
framework:
  modul:
    adi: Cam
    numarasi: 1
    log-etiketi: Çerçeve
minio:
  url: http://localhost:30005/
  accessKey: minio_accessKey
  secretKey: minio_secretKey
  bucketName: minio_bucketName
  acceptable-content-types: application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/x-citrix-jpeg,image/pjpeg,image/x-png,image/png,image/jpeg
  acceptable-file-types: pdf,docx,doc,jpg,jpeg,png