spring:
  application:
    name: backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/company-services
  datasource:
    url: jdbc:postgresql://localhost:5432/yusuf?charSet=UTF-8
    username: postgres
    password: root
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
  jpa:
    open-in-view: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
jwt:
  auth:
    converter:
      resource-id: projem-task
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:3000

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
logging:
  level:
    org.springframework.security: debug
    org.h2.jdbc: debug
server:
  port: 8080